-- SUPERSEDED — do not use this file.
--
-- It asked you to uncomment lines by hand, and one of the lines that had to STAY
-- a comment was an English sentence. Removing its comment markers produced:
--     ERROR: 42601: syntax error at or near "Check"
-- That was a bad design on my part, not a mistake by whoever ran it.
--
-- Use these two instead. Both are pure SQL: paste the whole file, press Run,
-- nothing to uncomment.
--
--   1. supabase/CLEANUP_STEP1_PREVIEW.sql   — shows what WOULD be deleted
--   2. supabase/CLEANUP_STEP2_DELETE.sql    — does the delete, and prints
--                                             exactly which rows it removed
--
-- Why the empty companies exist in the first place: GET /api/auth/me
-- auto-provisioned a company whenever it believed the user had none, and it
-- ignored query errors — so while the migration-021 embed was broken, every
-- retry minted another empty "…'s Workspace". That root cause is fixed (an
-- idempotency guard plus refusing to provision on a failed read), so no new
-- ones can appear. These files only clean up the ones already created.
