import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Navigation
    home: 'Home',
    sales: 'Sales',
    workflows: 'Workflows',
    aiChat: 'AI Chat',
    dashboards: 'Dashboards',
    integrations: 'Integrations',
    settings: 'Settings',
    help: 'Help',
    signOut: 'Sign Out',
    viewProfile: 'View Profile',

    // Home
    welcomeBack: 'WELCOME BACK!',
    hereIsWhatsHappening: "Here's what's happening with your sales today.",
    totalLeads: 'Total Leads',
    messagesSent: 'Messages Sent',
    conversionRate: 'Conversion Rate',
    pipelineValue: 'Pipeline Value',
    fromLastMonth: 'from last month',
    salesFunnel: 'Sales Funnel',
    yourLeadProgression: 'Your lead progression overview',
    recentActivity: 'Recent Activity',
    latestInteractions: 'Latest interactions',
    noRecentActivity: 'No recent activity',
    startByAdding: 'Start by adding leads or sending messages',
    gettingStarted: 'Getting Started',
    completeSteps: 'Complete these steps to set up your sales automation',
    defineYourICP: 'Define Your ICP',
    setUpICP: 'Set up your ideal customer profile criteria',
    importLeads: 'Import Leads',
    addLeadsManually: 'Add leads manually or import from CSV',
    createWorkflows: 'Create Workflows',
    buildAutomated: 'Build automated outreach sequences',
    addNewLead: 'Add New Lead',
    createMessage: 'Create Message',
    buildWorkflow: 'Build Workflow',

    // Sales
    leadManagement: 'Lead Management',
    manageLeads: 'Manage and track your leads through the sales funnel',
    kanbanView: 'Kanban View',
    listView: 'List View',
    qualificationView: 'Qualification Review',
    searchLeads: 'Search leads...',
    filterByStage: 'Filter by stage',
    allStages: 'All Stages',
    noLeadsFound: 'No leads found',
    addYourFirst: 'Add your first lead to get started',
    lists: 'Lists',
    allLists: 'All Lists',

    // Workflows
    workflowBuilder: 'Workflow Builder',
    createAndManage: 'Create and manage your automated outreach sequences',
    newWorkflow: 'New Workflow',
    activeWorkflows: 'Active Workflows',
    draftWorkflows: 'Draft Workflows',
    templates: 'Templates',
    optimizeLayout: 'Optimize Layout',
    createWorkflow: 'Create Workflow',

    // AI Chat
    aiSalesAgent: 'BMAPZ Sales Agent',
    intelligentProspecting: 'Intelligent Prospecting',
    askMeAnything: 'Ask me anything about lead research, outreach messages, or sales strategy...',
    send: 'Send',
    recordAudio: 'Record audio',
    stopRecording: 'Stop recording',
    transcribing: 'Transcribing...',

    // Dashboards
    dashboardsTitle: 'Dashboards',
    customizeYourView: 'Customize your data visualization',

    // Integrations
    integrationsTitle: 'Integrations',
    connectYourTools: 'Connect your tools and platforms',
    connected: 'Connected',
    disconnected: 'Disconnected',
    connect: 'Connect',
    disconnect: 'Disconnect',
    configured: 'Configured',

    // Settings
    settingsTitle: 'Settings',
    generalSettings: 'General Settings',
    companyProfile: 'Company Profile',
    icpSettings: 'ICP Settings',
    subscriptionPlan: 'Subscription Plan',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    briefing: 'Briefing',
    apiKeys: 'API Keys',
    companyInfo: 'Company Information',
    tofObjective: 'TOF Objective (Top of Funnel)',
    mofObjective: 'MOF Objective (Middle of Funnel)',
    bofObjective: 'BOF Objective (Bottom of Funnel)',
    billing: 'Billing',
    aiCredits: 'AI Credits',
    scanTokens: 'Scan Tokens',
    upgrade: 'Upgrade',
    currentPlan: 'Current Plan',

    // Pricing & Billing
    pricingTitle: 'Choose Your Plan',
    pricingSubtitle: 'Start with a 14-day free trial. No credit card required.',
    monthly: 'Monthly',
    annual: 'Annual',
    annualSave: 'Save 15%',
    perMonth: 'per month',
    creditsPerMonth: 'AI credits / month',
    contactsLabel: 'contacts',
    userSeats: 'users',
    companyProfiles: 'company profiles',
    fullScanTokens: 'Full Scan tokens / month',
    liteScansPerMonth: 'Lite Scan / month',
    extraUser: 'Extra user',
    extraCreditPack: 'Extra Credit Pack',
    fullScanAddon: 'Full Scan Token',
    extraCompanyProfile: 'Extra Company Profile',
    getStarted: 'Get started',
    currentPlanBadge: 'Current plan',
    addOns: 'Add-ons',
    addOnsDesc: 'Boost any plan with extra resources',
    cancellationFee: 'Annual Cancellation Fee',
    cancellationFeeDesc: 'Cancelling an annual plan before 12 months recovers the 15% discount on the months you used.',
    trialFullAccess: '14-day trial with full access — no credit card required',
    recommended: 'RECOMMENDED',
    // Usage tab
    aiCreditUsage: 'AI Credit Usage',
    totalCredits: 'Total Credits',
    usedThisCycle: 'Used This Cycle',
    remaining: 'Remaining',
    byFeature: 'By Feature',
    byModel: 'By Model',
    byUser: 'By User',
    recentActivityShort: 'Recent Activity',

    // Common
    save: 'Save Changes',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    create: 'Create',
    close: 'Close',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    leads: 'leads',
    messages: 'messages',
    generate: 'Generate',
    optimize: 'Optimize',
    addContext: 'Add context (optional)',
    contextPlaceholder: 'Extra context for AI: specific instructions, tone, target audience, product details...',
    generateNew: 'Generate New',
    optimizeExisting: 'Optimize Existing',

    // Lead statuses
    awareness: 'Awareness',
    leadCapture: 'Lead Capture',
    prospect: 'Prospect',
    mql: 'MQL',
    sql: 'SQL',
    opportunity: 'Opportunity',
    customer: 'Customer',

    // Growth funnel
    acquisition: 'Acquisition',
    activation: 'Activation',
    retention: 'Retention',
    revenue: 'Revenue',
    referral: 'Referral',

    // Blog
    blog: 'Blog',
    blogDescription: 'Create SEO-optimized blog posts and publish to your website',
    newPost: 'New Post',
    backToPosts: '← Back to Posts',
    postTitle: 'Post Title (H1)',
    urlSlug: 'URL Slug',
    keywords: 'Keywords',
    addKeyword: 'Add keyword...',
    metaDescription: 'Meta Description (150-160 chars)',
    content: 'Content (Markdown)',
    aiGenerate: 'AI Generate',
    saveDraft: 'Save Draft',
    updatePost: 'Update Post',
    publish: 'Publish',
    publishOptions: 'Publish Options',
    seoScore: 'SEO Score',
    wordCount: 'words',
    minWords: 'Min: 800 words',

    // Social Media
    socialMedia: 'Social Media',
    socialMediaDesc: 'Plan, create and schedule your social media content',
    planning: 'Planning',
    contentTab: 'Content',
    analytics: 'Analytics',
    posts: 'Posts',
    schedulePost: 'Schedule Post',
    editPost: 'Edit Post',
    deletePost: 'Delete Post',
    newPostBtn: 'New Post',
    generateWithAI: 'Generate with AI',
    boostSuggestion: 'Boost Suggestion',
    postedPosts: 'Published Posts',
    boostRecommended: 'Boost Recommended',
    selectPeriod: 'Select Period',
    last30Days: 'Last 30 Days',
    last7Days: 'Last 7 Days',
    last90Days: 'Last 90 Days',
    dayView: 'Day View',

    // Ads
    ads: 'Ads',
    adsDesc: 'Create AI-powered ad strategies and copies',
    strategy: 'Strategy',
    copy: 'Copy',
    creatives: 'Creatives',
    performance: 'Performance',
    generateStrategy: 'Generate Strategy',
    generateCopy: 'Generate Copy',
    abTest: 'A/B Test',
    variantA: 'Variant A',
    variantB: 'Variant B',
    extraContext: 'Extra Context (optional)',

    // Help
    helpCenter: 'Help Center',
    helpDesc: 'Find answers, ask our AI, or contact support',
    searchHelp: 'Search help or ask the AI assistant...',
    askAI: 'Ask AI',
    emailSupport: 'Email Support',
    liveChat: 'Live Chat (WhatsApp)',
    aiAssistant: 'AI Assistant',
    stillNeedHelp: 'Still need help?',
    supportReady: 'Our support team is ready to assist you',
    documentation: 'Documentation',
    videoTutorials: 'Video Tutorials',
    apiReference: 'API Reference',
    gettingStartedFaq: 'Getting Started',
    enterpriseOnly: 'Enterprise plan required',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyDesc: 'Read how BMAPZ handles and protects your data',
    viewPolicy: 'View Policy',

    // Analytics / Workflow Analytics
    workflowAnalytics: 'Workflow Analytics',
    recommendations: 'Recommendations',
    goToPage: 'Go to Page',

    // Brand Scan
    brandScan: 'Brand Scan',
    importantInfo: 'Important Information',

    // Lead Lists
    dynamicList: 'Dynamic List',
    autoAddsLeads: 'Auto-adds leads based on rules',
    createList: 'Create New List',
    editList: 'Edit List',
    listName: 'List Name',
    description: 'Description',

    // Workflow Builder shortcuts
    shortcutUndo: 'Ctrl+Z: Undo',
    shortcutRedo: 'Ctrl+Y: Redo',
    shortcutZoom: 'Scroll: Zoom',
    shortcutPan: 'Right-click drag: Pan',
    shortcutSelect: 'Shift+Click: Multi-select',
    shortcutBox: 'Left-drag: Box select',

    // Navigation labels (sidebar / mobile)
    inbox: 'Inbox',
    profile: 'Profile',
    signOut: 'Sign Out',
    marketing: 'Marketing',
    contentAndAI: 'Content & AI',
    tools: 'Tools',
    account: 'Account',
    admin: 'Admin',
    companyAdmin: 'Company Admin',
    systemAdmin: 'System Admin',
    aiOutputs: 'AI Outputs',
    textTemplates: 'Text Templates',
    brandScanNav: 'Brand Scan',
    more: 'More',

    // Workflows page
    buildAutomateOptimize: 'Build, automate, and optimize sales sequences with AI',
    searchWorkflows: 'Search workflows...',
    activeCount: 'Active',
    draftsCount: 'Drafts',
    inactiveCount: 'Inactive',
    templatesCount: 'Templates',
    noWorkflows: 'No {status} workflows',
    createOneToStart: 'Create one to get started',
    steps: 'steps',
    enrolled: 'enrolled',
    pause: 'Pause',
    activate: 'Activate',
    duplicate: 'Duplicate',
    useTemplate: 'Use Template',
    useAsTemplate: 'Use as Template',
    workflowCreatedFromTemplate: 'Workflow created from template!',
    appWideTemplates: 'These are app-wide workflow templates accessible to all users. Use them as a starting point for your custom workflows.',
    workflowCreated: 'Workflow created! Find it in Active/Draft tabs.',
    deleted: 'Deleted',
    duplicated: 'Duplicated',
    companyNotLoaded: 'Company not loaded',

    // Workflow Quick Start steps
    wfQs1: "Click 'New Workflow' to open the visual builder. Drag node types from the left panel onto the canvas.",
    wfQs2: "Connect nodes by clicking the output port (bottom circle) of one node and the input port (top circle) of another.",
    wfQs3: "Use Condition nodes to branch the flow based on lead behavior (replied, opened email, booked meeting, etc.).",
    wfQs4: "Activate a workflow to start enrolling leads. You can pause it anytime and track enrollment counts on each card.",

    // Workflow templates
    wfT1Name: 'Cold Email Sequence',
    wfT1Desc: '5-step email outreach: intro, follow-up x3, breakup email. Targets ICP contacts.',
    wfT2Name: 'LinkedIn Prospecting',
    wfT2Desc: 'Connection request + 3 follow-up messages over 14 days. Personalized for each lead.',
    wfT3Name: 'WhatsApp Nurture',
    wfT3Desc: 'Warm WhatsApp sequence: value message, case study, meeting ask. 7-day cadence.',
    wfT4Name: 'Lead Qualification',
    wfT4Desc: 'Automatically score and qualify leads based on ICP criteria. Moves to CRM stages.',
    wfT5Name: 'Re-engagement Campaign',
    wfT5Desc: 'Win back cold leads: personalized message + special offer + final follow-up.',
    wfT6Name: 'New Lead Welcome',
    wfT6Desc: 'Instant welcome message when a new lead is added + schedule intro call.',

    // Ads page
    adsTitle: 'Ads',
    adsPowered: 'AI-powered ad strategy and copy creation • Pre-filled from your Settings',
    saved: 'Saved',
    campaigns: 'Campaigns',
    createAd: 'Create Ad',
    optimize: 'Optimize',
    publishCampaignStrategy: 'Publish Campaign Strategy',
    updateExistingCampaign: 'Update Existing Campaign',
    publishAdCopies: 'Publish Ad Copies',
    updateAdCopies: 'Update Ad Copies',
    selectObjective: 'Select a campaign objective',
    generationFailed: 'Generation failed',
    strategyGenerated: 'Strategy generated!',
    copiesGenerated: 'Ad copies generated!',
    adsQs1: "Fill in your campaign objective and platform in the Strategy tab, then click 'Generate Strategy' to get a full AI-powered campaign plan.",
    adsQs2: "Switch to the Copy tab to generate ad copy for each funnel stage (TOF, MOF, BOF) aligned to your strategy.",
    adsQs3: "Use the Creatives tab to generate design briefs and test A/B variations for your ad visuals.",
    adsQs4: "Connect your Meta or Google Ads account in Settings → API Keys to import real performance data and get data-driven recommendations.",

    // Settings page tabs
    general: 'General',
    company: 'Company',
    icpTab: 'ICP Settings',
    apiKeysTab: 'API Keys',
    aiSettingsTab: 'AI Settings',
    usageTab: 'Usage',
    subscriptionTab: 'Subscription',
    preferences: 'Preferences',
    chooseLanguage: 'Choose your preferred language',
    companyInformation: 'Company Information',
    companyName: 'Company Name',
    website: 'Website',
    industryNiche: 'Industry / Niche',
    yearsInBusiness: 'Years in Business',
    businessModel: 'Business Model',
    averageTicket: 'Average Ticket Size',
    repurchaseCycle: 'Average Repurchase Cycle',
    geographicMarket: 'Geographic Market',
    marketingStructure: 'Marketing Structure',
    salesStructure: 'Sales Structure',
    mainProductsServices: 'Main Product(s) or Service(s)',
    valuePropositions: 'Value Propositions',
    addValueProp: 'Add a value proposition',
    saveCompanyProfile: 'Save Company Profile',
    selectModel: 'Select model',
    selectMarket: 'Select market',

    // Settings briefing
    strategicBriefing: 'Strategic Briefing',
    briefingDesc: 'This briefing is used as context to improve AI outputs and task automation. Questions are not mandatory but improve AI quality significantly.',
    currentScenario: 'Current Scenario',
    primaryObjectives: 'Primary Objectives',
    positioningDiff: 'Positioning & Differentiation',
    offerProducts: 'Offer & Products',
    contentStrategy: 'Content Strategy',
    mediaBudget: 'Media & Budget',
    bottlenecks: 'Bottlenecks & Retention',
    brandIdentity: 'Brand Identity & Visuals',
    differentiators: 'Differentiators',
    customerJourney: 'Customer Journey',
    seasonality: 'Seasonality & Events',
    saveStrategicBriefing: 'Save Strategic Briefing',

    // Briefing form labels
    currentMarketingQ: 'Is the company currently investing in marketing campaigns?',
    whichChannels: 'If yes, which channels?',
    mainChallenge: 'Main current challenge:',
    structuredFunnel: 'Is there a structured funnel?',
    historicalData: 'Is the historical data organized?',
    selectPriorities: 'Select priorities:',
    funnelStageObjectives: 'Funnel Stage Objectives',
    tofDesc: 'Awareness & discovery',
    mofDesc: 'Consideration & nurturing',
    bofDesc: 'Conversion & closing',
    revenueTarget: 'Revenue Target',
    leadTarget: 'Lead Target',
    expectedRoi: 'Expected ROI',
    positioningToday: 'How does the company position itself today?',
    desiredPerception: 'How does it want to be perceived?',
    competitiveAdvantages: 'Main competitive advantages',
    doNotCommunicate: 'What should NOT be communicated?',
    toneOfVoice: 'Desired tone of voice:',
    directCompetitors: 'Direct Competitors',
    marketReferences: 'Market References (brands you admire)',
    productService: 'Product / Service',
    whatSold: 'What is truly being sold?',
    whatTransformation: 'What transformation does it generate?',
    technicalDifferentiator: 'Technical differentiator (that few competitors can explain)',
    recurrenceSubscription: 'Recurrence / Subscription?',
    upsellBundling: 'Upsell or strategic bundling?',
    primaryPlatforms: 'Primary platform(s):',
    priorityFormats: 'Priority formats:',
    postingFrequency: 'Ideal posting frequency (weekly/monthly)',
    mainStrategicFocus: 'Main strategic focus:',
    contentHookType: 'Content hook type (video):',
    performanceStrategy: 'Performance Strategy (Paid Media)',
    monthlyBudget: 'Average Monthly Budget',
    campaignStructure: 'Current Campaign Structure',
    mostImportantKPIs: 'Most important KPIs:',
    retentionStrategyQ: 'Is there a retention strategy?',
    coreMessage: 'Core Message',
    believeSentence: '"We believe that ___________________."',
    existsSentence: '"Our company exists to ___________________."',
    unlikeSentence: '"Unlike companies that ______, we ______."',
    successMetrics: 'Success Metrics',
    howWeKnow: 'How will we know this is working?',
    expectedTimeframe: 'Expected time frame for results',
    ideal6Months: 'Ideal scenario in 6 months',

    // Settings ICP
    icpTitle: 'Ideal Customer Profile (ICP)',
    icpDesc: 'Define your ideal customer to get better AI outputs, scoring, and targeting.',
    targetIndustries: 'Target Industries',
    addIndustry: 'Add industry...',
    companySizes: 'Company Sizes',
    locations: 'Locations',
    addLocation: 'Add location...',
    jobTitles: 'Job Titles / Roles',
    addJobTitle: 'Add job title...',
    painPoints: 'Pain Points',
    addPainPoint: 'Add pain point...',
    budgetRange: 'Budget Range',
    decisionCriteria: 'Decision Criteria',
    primaryAudience: 'Primary Audience',
    secondaryAudience: 'Secondary Audience',
    decisionMakerProfile: 'Decision-Maker Profile',
    mainDesires: 'Main Desires / Goals',
    commonObjections: 'Common Objections',
    awarenessLevel: 'Awareness Level',
    saveICP: 'Save ICP Settings',
    notForLabel: 'Who is this NOT for?',

    // Settings AI
    agentName: 'Agent Name',
    agentNameDesc: 'Customize the name of your AI agent shown in the sidebar and chat.',
    saveAgentName: 'Save Agent Name',
    aiConfiguration: 'AI Configuration',
    aiConfigDesc: 'Configure AI image generation and your personal AI agent name.',
    personalAgentName: 'Personal AI Agent Name',
    personalAgentDesc: 'This name appears in the sidebar and AI chat. Your team will see this label.',
    agentNameHint: 'Leave blank to use the default "Bmapz AI".',
    imageProvider: 'Image Generation Provider',
    imageProviderDesc: 'Choose which AI generates images in the platform (ads creatives, social posts, etc.)',
    dalleModel: 'DALL-E Model:',

    // Subscription
    subscriptionDesc: 'Manage your subscription, credits and add-ons',
    seeInBilling: 'See in Billing',
    manageSubscription: 'Manage Subscription',
    viewPlans: 'View Plans',
    settingsSaved: 'Settings saved',

    // QuickStartGuide
    gotItSkip: 'Got it, skip',
    gotIt: 'Got it!',

    // Admin panel
    adminPanel: 'Admin Panel',
    adminDesc: 'Full platform control — users, companies, subscriptions & billing',
    companies: 'Companies',
    users: 'Users',
    activeSubs: 'Active Subs',
    pending: 'Pending',
    pendingApproval: 'purchase(s) pending manual approval',
    plan: 'Plan',
    status: 'Status',
    billingCycle: 'Billing Cycle',
    priceBRL: 'Price (BRL/mo)',
    aiCreditsTotal: 'AI Credits Total',
    scanTokensLabel: 'Scan Tokens',
    actions: 'Actions',
    editSubscription: 'Edit Subscription',
    grantCredits: 'Grant Credits',
    inviteUser: 'Invite User',
    createCompany: 'Create Company',
    email: 'Email',
    role: 'Role',
    creditsToGrant: 'Credits to Grant',
    reason: 'Reason',
    trialDays: 'Trial Days',

    // Social Media
    socialMediaTitle: 'Social Media',
    socialMediaSubtitle: 'Plan, create and schedule content + AI-powered performance optimization',
    aiOptimize: 'AI Optimize',
    connectSocialAccounts: 'Connect social accounts in Settings → API Keys to auto-publish',
    noPostsYet: 'No posts yet',
    noPostsScheduled: 'No posts scheduled yet',
    platforms: 'Platforms',
    addMedia: 'Add Media',
    performance: 'Performance',
    sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat',
    smQs1: "Use the calendar to plan and schedule posts. Click any day to create a post for that date.",
    smQs2: "Use the 'Generate with AI' button to create platform-optimized content for Instagram, LinkedIn, and more.",
    smQs3: "Connect your social accounts in Settings → API Keys to enable direct publishing.",
    smQs4: "Use the Analytics tab to track performance and the AI Optimize button for improvement suggestions.",

    // Profile
    profileTitle: 'Profile',
    myProfile: 'My Profile',
    managePersonalInfo: 'Manage your personal information',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    timezone: 'Timezone',
    emailCannotChange: 'Email cannot be changed',
    accountInfo: 'Account Information',
    memberSince: 'Member Since',
    accountType: 'Account Type',
    profilePicture: 'Profile Picture',
    uploadPhoto: 'Upload Photo',
    changePhoto: 'Change Photo',
    saving: 'Saving...',
    profileSaved: 'Profile saved!',
    profileUpdated: 'Profile updated successfully',
    failedToSave: 'Failed to save profile',
    failedToUpdate: 'Failed to update profile',
    failedToUpload: 'Failed to upload image',
    selectImageFile: 'Please select an image file',
    imageTooLarge: 'Image must be less than 5MB',
    profilePictureUpdated: 'Profile picture updated',

    // Home QuickStart
    homeQs1: "This dashboard shows your key metrics, sales funnel progression, and recent activity at a glance.",
    homeQs2: "Complete the 'Getting Started' steps below to unlock the full power of BMAPZ.",
    homeQs3: "Use the quick-action buttons above to jump right in.",
    homeQs4: "The AI Agent in the sidebar can help you write messages, build strategies, and analyze leads.",

    // Sales QuickStart
    salesQs1: "Add leads manually with the '+ Add New Lead' button, or import them in bulk from the Sales menu.",
    salesQs2: "Use Kanban view to drag leads between funnel stages, or switch to List view for a spreadsheet-style overview.",
    salesQs3: "Click any lead card to open its full profile — add notes, send messages, run AI analysis, and enroll in workflows.",
    salesQs4: "Use the Filters panel to narrow down leads by ICP score, value, source, or list membership.",

    // Sales / Lead management additional
    leadUpdated: 'Lead updated',
    noActiveWorkflows: 'No active workflows',
    noDraftWorkflows: 'No draft workflows',
    noInactiveWorkflows: 'No inactive workflows',

    // Integrations
    stepByStep: 'Step-by-step guide',
    openPlatform: 'Open Platform →',
    awaitingSetup: 'Awaiting platform setup',
    connectionFailed: 'Connection failed',
    connected: 'Connected',
    testingConnection: 'Testing connection...',
    saveAndConnect: 'Save & Connect',
    howToConnect: 'How to connect',

    // Common extras
    searchPlaceholder: 'Search...',
    noResultsFound: 'No results found',
    copyToClipboard: 'Copy to clipboard',
    copied: 'Copied!',
    viewAll: 'View all',
    seeAll: 'See all',
    required: 'Required',
    optional: 'optional',
    na: 'N/A',
    yes: 'Yes',
    no: 'No',
    on: 'On',
    off: 'Off',
    active: 'Active',
    draft: 'Draft',
    inactive: 'Inactive',
    complete: 'Complete',
    generating: 'Generating...',
    noData: 'No data available',
  },
  'pt-BR': {
    // Navigation
    home: 'Início',
    sales: 'Vendas',
    workflows: 'Fluxos',
    aiChat: 'Chat IA',
    dashboards: 'Dashboards',
    integrations: 'Integrações',
    settings: 'Configurações',
    help: 'Ajuda',
    signOut: 'Sair',
    viewProfile: 'Ver Perfil',

    // Home
    welcomeBack: 'BEM-VINDO DE VOLTA!',
    hereIsWhatsHappening: 'Veja o que está acontecendo com suas vendas hoje.',
    totalLeads: 'Total de Leads',
    messagesSent: 'Mensagens Enviadas',
    conversionRate: 'Taxa de Conversão',
    pipelineValue: 'Valor do Pipeline',
    fromLastMonth: 'do mês passado',
    salesFunnel: 'Funil de Vendas',
    yourLeadProgression: 'Visão geral da progressão dos leads',
    recentActivity: 'Atividade Recente',
    latestInteractions: 'Últimas interações',
    noRecentActivity: 'Sem atividade recente',
    startByAdding: 'Comece adicionando leads ou enviando mensagens',
    gettingStarted: 'Primeiros Passos',
    completeSteps: 'Complete estas etapas para configurar sua automação de vendas',
    defineYourICP: 'Defina seu ICP',
    setUpICP: 'Configure os critérios do perfil de cliente ideal',
    importLeads: 'Importar Leads',
    addLeadsManually: 'Adicione leads manualmente ou importe do CSV',
    createWorkflows: 'Criar Fluxos',
    buildAutomated: 'Construa sequências de contato automatizadas',
    addNewLead: 'Novo Lead',
    createMessage: 'Criar Mensagem',
    buildWorkflow: 'Criar Fluxo',

    // Sales
    leadManagement: 'Gestão de Leads',
    manageLeads: 'Gerencie e acompanhe seus leads pelo funil de vendas',
    kanbanView: 'Visão Kanban',
    listView: 'Visão de Lista',
    qualificationView: 'Revisão de Qualificação',
    searchLeads: 'Buscar leads...',
    filterByStage: 'Filtrar por etapa',
    allStages: 'Todos os Estágios',
    noLeadsFound: 'Nenhum lead encontrado',
    addYourFirst: 'Adicione seu primeiro lead para começar',
    lists: 'Listas',
    allLists: 'Todas as Listas',

    // Workflows
    workflowBuilder: 'Construtor de Fluxos',
    createAndManage: 'Crie e gerencie suas sequências de contato automatizadas',
    newWorkflow: 'Novo Fluxo',
    activeWorkflows: 'Fluxos Ativos',
    draftWorkflows: 'Rascunhos',
    templates: 'Modelos',
    optimizeLayout: 'Otimizar Layout',
    createWorkflow: 'Criar Fluxo',

    // AI Chat
    aiSalesAgent: 'Agente BMAPZ',
    intelligentProspecting: 'Prospecção Inteligente',
    askMeAnything: 'Pergunte-me sobre pesquisa de leads, mensagens de contato ou estratégia de vendas...',
    send: 'Enviar',
    recordAudio: 'Gravar áudio',
    stopRecording: 'Parar gravação',
    transcribing: 'Transcrevendo...',

    // Dashboards
    dashboardsTitle: 'Dashboards',
    customizeYourView: 'Personalize sua visualização de dados',

    // Integrations
    integrationsTitle: 'Integrações',
    connectYourTools: 'Conecte suas ferramentas e plataformas',
    connected: 'Conectado',
    disconnected: 'Desconectado',
    connect: 'Conectar',
    disconnect: 'Desconectar',
    configured: 'Configurado',

    // Settings
    settingsTitle: 'Configurações',
    generalSettings: 'Configurações Gerais',
    companyProfile: 'Perfil da Empresa',
    icpSettings: 'Configurações de ICP',
    subscriptionPlan: 'Plano de Assinatura',
    language: 'Idioma',
    theme: 'Tema',
    darkMode: 'Modo Escuro',
    lightMode: 'Modo Claro',
    briefing: 'Briefing',
    apiKeys: 'Chaves de API',
    companyInfo: 'Informações da Empresa',
    tofObjective: 'Objetivo TOF (Topo do Funil)',
    mofObjective: 'Objetivo MOF (Meio do Funil)',
    bofObjective: 'Objetivo BOF (Fundo do Funil)',
    billing: 'Cobrança',
    aiCredits: 'Créditos de IA',
    scanTokens: 'Scan Tokens',
    upgrade: 'Fazer Upgrade',
    currentPlan: 'Plano Atual',

    // Pricing & Billing
    pricingTitle: 'Escolha Seu Plano',
    pricingSubtitle: 'Comece com 14 dias grátis. Sem cartão de crédito.',
    monthly: 'Mensal',
    annual: 'Anual',
    annualSave: 'Economize 15%',
    perMonth: 'por mês',
    creditsPerMonth: 'créditos de IA / mês',
    contactsLabel: 'contatos',
    userSeats: 'usuários',
    companyProfiles: 'perfis de empresa',
    fullScanTokens: 'Full Scan tokens / mês',
    liteScansPerMonth: 'Lite Scan / mês',
    extraUser: 'Usuário Adicional',
    extraCreditPack: 'Pacote de Créditos Extra',
    fullScanAddon: 'Token de Full Scan',
    extraCompanyProfile: 'Perfil de Empresa Adicional',
    getStarted: 'Começar',
    currentPlanBadge: 'Plano atual',
    addOns: 'Add-ons',
    addOnsDesc: 'Potencialize qualquer plano com recursos extras',
    cancellationFee: 'Taxa de Cancelamento Anual',
    cancellationFeeDesc: 'Cancelar plano anual antes de 12 meses recupera o desconto de 15% sobre os meses utilizados.',
    trialFullAccess: '14 dias de trial com acesso completo — sem cartão de crédito',
    recommended: 'RECOMENDADO',
    // Usage tab
    aiCreditUsage: 'Uso de Créditos de IA',
    totalCredits: 'Total de Créditos',
    usedThisCycle: 'Usados Neste Ciclo',
    remaining: 'Restantes',
    byFeature: 'Por Funcionalidade',
    byModel: 'Por Modelo',
    byUser: 'Por Usuário',
    recentActivityShort: 'Atividade Recente',

    // Common
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    create: 'Criar',
    close: 'Fechar',
    loading: 'Carregando...',
    error: 'Erro',
    success: 'Sucesso',
    confirm: 'Confirmar',
    back: 'Voltar',
    next: 'Próximo',
    leads: 'leads',
    messages: 'mensagens',
    generate: 'Gerar',
    optimize: 'Otimizar',
    addContext: 'Adicionar contexto (opcional)',
    contextPlaceholder: 'Contexto extra para a IA: instruções específicas, tom, público-alvo, detalhes do produto...',
    generateNew: 'Gerar Novo',
    optimizeExisting: 'Otimizar Existente',

    // Lead statuses
    awareness: 'Consciência',
    leadCapture: 'Captura de Lead',
    prospect: 'Prospecto',
    mql: 'MQL',
    sql: 'SQL',
    opportunity: 'Oportunidade',
    customer: 'Cliente',

    // Growth funnel
    acquisition: 'Aquisição',
    activation: 'Ativação',
    retention: 'Retenção',
    revenue: 'Receita',
    referral: 'Indicação',

    // Blog
    blog: 'Blog',
    blogDescription: 'Crie artigos otimizados para SEO e publique no seu site',
    newPost: 'Novo Artigo',
    backToPosts: '← Voltar aos Artigos',
    postTitle: 'Título do Artigo (H1)',
    urlSlug: 'Slug da URL',
    keywords: 'Palavras-chave',
    addKeyword: 'Adicionar palavra-chave...',
    metaDescription: 'Meta Descrição (150-160 caracteres)',
    content: 'Conteúdo (Markdown)',
    aiGenerate: 'Gerar com IA',
    saveDraft: 'Salvar Rascunho',
    updatePost: 'Atualizar Artigo',
    publish: 'Publicar',
    publishOptions: 'Opções de Publicação',
    seoScore: 'Score SEO',
    wordCount: 'palavras',
    minWords: 'Mínimo: 800 palavras',

    // Social Media
    socialMedia: 'Redes Sociais',
    socialMediaDesc: 'Planeje, crie e agende seu conteúdo nas redes sociais',
    planning: 'Planejamento',
    contentTab: 'Conteúdo',
    analytics: 'Análise',
    posts: 'Posts',
    schedulePost: 'Agendar Post',
    editPost: 'Editar Post',
    deletePost: 'Excluir Post',
    newPostBtn: 'Novo Post',
    generateWithAI: 'Gerar com IA',
    boostSuggestion: 'Sugestão de Impulsionamento',
    postedPosts: 'Posts Publicados',
    boostRecommended: 'Impulsionamento Recomendado',
    selectPeriod: 'Selecionar Período',
    last30Days: 'Últimos 30 Dias',
    last7Days: 'Últimos 7 Dias',
    last90Days: 'Últimos 90 Dias',
    dayView: 'Visão do Dia',

    // Ads
    ads: 'Anúncios',
    adsDesc: 'Crie estratégias e textos de anúncios com IA',
    strategy: 'Estratégia',
    copy: 'Copys',
    creatives: 'Criativos',
    performance: 'Desempenho',
    generateStrategy: 'Gerar Estratégia',
    generateCopy: 'Gerar Copy',
    abTest: 'Teste A/B',
    variantA: 'Variante A',
    variantB: 'Variante B',
    extraContext: 'Contexto Extra (opcional)',

    // Help
    helpCenter: 'Central de Ajuda',
    helpDesc: 'Encontre respostas, pergunte à IA ou entre em contato com o suporte',
    searchHelp: 'Buscar ajuda ou perguntar à IA...',
    askAI: 'Perguntar à IA',
    emailSupport: 'Suporte por E-mail',
    liveChat: 'Chat ao Vivo (WhatsApp)',
    aiAssistant: 'Assistente IA',
    stillNeedHelp: 'Ainda precisa de ajuda?',
    supportReady: 'Nossa equipe de suporte está pronta para ajudar',
    documentation: 'Documentação',
    videoTutorials: 'Tutoriais em Vídeo',
    apiReference: 'Referência de API',
    gettingStartedFaq: 'Primeiros Passos',
    enterpriseOnly: 'Plano Enterprise necessário',
    privacyPolicy: 'Política de Privacidade',
    privacyPolicyDesc: 'Leia como o BMAPZ trata e protege seus dados',
    viewPolicy: 'Ver Política',

    // Analytics / Workflow Analytics
    workflowAnalytics: 'Análise de Fluxos',
    recommendations: 'Recomendações',
    goToPage: 'Ir para Página',

    // Brand Scan
    brandScan: 'Brand Scan',
    importantInfo: 'Informações Importantes',

    // Lead Lists
    dynamicList: 'Lista Dinâmica',
    autoAddsLeads: 'Adiciona leads automaticamente com base em regras',
    createList: 'Criar Nova Lista',
    editList: 'Editar Lista',
    listName: 'Nome da Lista',
    description: 'Descrição',

    // Workflow Builder shortcuts
    shortcutUndo: 'Ctrl+Z: Desfazer',
    shortcutRedo: 'Ctrl+Y: Refazer',
    shortcutZoom: 'Scroll: Zoom',
    shortcutPan: 'Botão dir. do mouse: Mover',
    shortcutSelect: 'Shift+Clique: Multi-seleção',
    shortcutBox: 'Arrastar: Seleção em área',

    // Navigation labels
    inbox: 'Caixa de Entrada',
    profile: 'Perfil',
    signOut: 'Sair',
    marketing: 'Marketing',
    contentAndAI: 'Conteúdo & IA',
    tools: 'Ferramentas',
    account: 'Conta',
    admin: 'Admin',
    companyAdmin: 'Admin da Empresa',
    systemAdmin: 'Admin do Sistema',
    aiOutputs: 'Saídas de IA',
    textTemplates: 'Modelos de Texto',
    brandScanNav: 'Brand Scan',
    more: 'Mais',

    // Workflows page
    buildAutomateOptimize: 'Construa, automatize e otimize sequências de vendas com IA',
    searchWorkflows: 'Buscar fluxos...',
    activeCount: 'Ativos',
    draftsCount: 'Rascunhos',
    inactiveCount: 'Inativos',
    templatesCount: 'Modelos',
    noWorkflows: 'Nenhum fluxo {status}',
    createOneToStart: 'Crie um para começar',
    steps: 'etapas',
    enrolled: 'inscritos',
    pause: 'Pausar',
    activate: 'Ativar',
    duplicate: 'Duplicar',
    useTemplate: 'Usar Modelo',
    useAsTemplate: 'Usar como Modelo',
    workflowCreatedFromTemplate: 'Fluxo criado a partir do modelo!',
    appWideTemplates: 'Estes são modelos de fluxo disponíveis para todos os usuários. Use-os como ponto de partida para seus fluxos personalizados.',
    workflowCreated: 'Fluxo criado! Encontre-o nas abas Ativos/Rascunhos.',
    deleted: 'Excluído',
    duplicated: 'Duplicado',
    companyNotLoaded: 'Empresa não carregada',

    // Workflow Quick Start steps
    wfQs1: "Clique em 'Novo Fluxo' para abrir o construtor visual. Arraste os tipos de nó do painel esquerdo para o canvas.",
    wfQs2: "Conecte nós clicando na porta de saída (círculo inferior) de um nó e na porta de entrada (círculo superior) de outro.",
    wfQs3: "Use nós de Condição para ramificar o fluxo com base no comportamento do lead (respondeu, abriu e-mail, agendou reunião, etc.).",
    wfQs4: "Ative um fluxo para começar a inscrever leads. Você pode pausá-lo a qualquer momento e acompanhar a contagem de inscrições em cada card.",

    // Workflow templates
    wfT1Name: 'Sequência de E-mail Frio',
    wfT1Desc: 'Outreach de e-mail em 5 etapas: introdução, follow-up x3, e-mail de encerramento. Foca em contatos ICP.',
    wfT2Name: 'Prospecção no LinkedIn',
    wfT2Desc: 'Pedido de conexão + 3 mensagens de follow-up em 14 dias. Personalizado para cada lead.',
    wfT3Name: 'Nutrição no WhatsApp',
    wfT3Desc: 'Sequência no WhatsApp: mensagem de valor, case de sucesso, solicitação de reunião. Cadência de 7 dias.',
    wfT4Name: 'Qualificação de Leads',
    wfT4Desc: 'Pontua e qualifica leads automaticamente com base em critérios de ICP. Avança nos estágios do CRM.',
    wfT5Name: 'Campanha de Re-engajamento',
    wfT5Desc: 'Reconquiste leads frios: mensagem personalizada + oferta especial + follow-up final.',
    wfT6Name: 'Boas-Vindas a Novo Lead',
    wfT6Desc: 'Mensagem de boas-vindas instantânea quando um novo lead é adicionado + agendamento de chamada introdutória.',

    // Ads page
    adsTitle: 'Anúncios',
    adsPowered: 'Estratégia e textos de anúncios com IA • Pré-preenchido das suas Configurações',
    saved: 'Salvos',
    campaigns: 'Campanhas',
    createAd: 'Criar Anúncio',
    optimize: 'Otimizar',
    publishCampaignStrategy: 'Publicar Estratégia de Campanha',
    updateExistingCampaign: 'Atualizar Campanha Existente',
    publishAdCopies: 'Publicar Textos de Anúncio',
    updateAdCopies: 'Atualizar Textos de Anúncio',
    selectObjective: 'Selecione um objetivo de campanha',
    generationFailed: 'Falha na geração',
    strategyGenerated: 'Estratégia gerada!',
    copiesGenerated: 'Textos de anúncio gerados!',
    adsQs1: "Preencha seu objetivo de campanha e plataforma na aba Estratégia, depois clique em 'Gerar Estratégia' para obter um plano completo com IA.",
    adsQs2: "Vá para a aba Copy para gerar textos de anúncio para cada etapa do funil (TOF, MOF, BOF) alinhados à sua estratégia.",
    adsQs3: "Use a aba Criativos para gerar briefings de design e testar variações A/B para seus visuais de anúncio.",
    adsQs4: "Conecte sua conta Meta ou Google Ads em Configurações → Chaves de API para importar dados reais e obter recomendações baseadas em dados.",

    // Settings page tabs
    general: 'Geral',
    company: 'Empresa',
    icpTab: 'Config. ICP',
    apiKeysTab: 'Chaves de API',
    aiSettingsTab: 'Config. IA',
    usageTab: 'Uso',
    subscriptionTab: 'Assinatura',
    preferences: 'Preferências',
    chooseLanguage: 'Escolha seu idioma preferido',
    companyInformation: 'Informações da Empresa',
    companyName: 'Nome da Empresa',
    website: 'Website',
    industryNiche: 'Indústria / Nicho',
    yearsInBusiness: 'Anos de Operação',
    businessModel: 'Modelo de Negócio',
    averageTicket: 'Ticket Médio',
    repurchaseCycle: 'Ciclo Médio de Recompra',
    geographicMarket: 'Mercado Geográfico',
    marketingStructure: 'Estrutura de Marketing',
    salesStructure: 'Estrutura de Vendas',
    mainProductsServices: 'Principal(is) Produto(s) ou Serviço(s)',
    valuePropositions: 'Propostas de Valor',
    addValueProp: 'Adicionar proposta de valor',
    saveCompanyProfile: 'Salvar Perfil da Empresa',
    selectModel: 'Selecionar modelo',
    selectMarket: 'Selecionar mercado',

    // Settings briefing
    strategicBriefing: 'Briefing Estratégico',
    briefingDesc: 'Este briefing é usado como contexto para melhorar os outputs de IA e automação de tarefas. As perguntas não são obrigatórias, mas melhoram significativamente a qualidade da IA.',
    currentScenario: 'Cenário Atual',
    primaryObjectives: 'Objetivos Primários',
    positioningDiff: 'Posicionamento & Diferenciação',
    offerProducts: 'Oferta & Produtos',
    contentStrategy: 'Estratégia de Conteúdo',
    mediaBudget: 'Mídia & Orçamento',
    bottlenecks: 'Gargalos & Retenção',
    brandIdentity: 'Identidade Visual & Marca',
    differentiators: 'Diferenciais',
    customerJourney: 'Jornada do Cliente',
    seasonality: 'Sazonalidade & Eventos',
    saveStrategicBriefing: 'Salvar Briefing Estratégico',

    // Briefing form labels
    currentMarketingQ: 'A empresa está investindo atualmente em campanhas de marketing?',
    whichChannels: 'Se sim, quais canais?',
    mainChallenge: 'Principal desafio atual:',
    structuredFunnel: 'Existe um funil estruturado?',
    historicalData: 'Os dados históricos estão organizados?',
    selectPriorities: 'Selecione as prioridades:',
    funnelStageObjectives: 'Objetivos por Etapa do Funil',
    tofDesc: 'Consciência e descoberta',
    mofDesc: 'Consideração e nutrição',
    bofDesc: 'Conversão e fechamento',
    revenueTarget: 'Meta de Receita',
    leadTarget: 'Meta de Leads',
    expectedRoi: 'ROI Esperado',
    positioningToday: 'Como a empresa se posiciona hoje?',
    desiredPerception: 'Como ela quer ser percebida?',
    competitiveAdvantages: 'Principais vantagens competitivas',
    doNotCommunicate: 'O que NÃO deve ser comunicado?',
    toneOfVoice: 'Tom de voz desejado:',
    directCompetitors: 'Concorrentes Diretos',
    marketReferences: 'Referências de Mercado (marcas que admira)',
    productService: 'Produto / Serviço',
    whatSold: 'O que realmente está sendo vendido?',
    whatTransformation: 'Que transformação ele gera?',
    technicalDifferentiator: 'Diferencial técnico (que poucos concorrentes conseguem explicar)',
    recurrenceSubscription: 'Recorrência / Assinatura?',
    upsellBundling: 'Upsell ou bundling estratégico?',
    primaryPlatforms: 'Plataforma(s) principal(is):',
    priorityFormats: 'Formatos prioritários:',
    postingFrequency: 'Frequência ideal de postagem (semanal/mensal)',
    mainStrategicFocus: 'Foco estratégico principal:',
    contentHookType: 'Tipo de gancho de conteúdo (vídeo):',
    performanceStrategy: 'Estratégia de Performance (Mídia Paga)',
    monthlyBudget: 'Orçamento Médio Mensal',
    campaignStructure: 'Estrutura Atual de Campanha',
    mostImportantKPIs: 'KPIs mais importantes:',
    retentionStrategyQ: 'Existe uma estratégia de retenção?',
    coreMessage: 'Mensagem Central',
    believeSentence: '"Nós acreditamos que ___________________."',
    existsSentence: '"Nossa empresa existe para ___________________."',
    unlikeSentence: '"Ao contrário de empresas que ______, nós ______."',
    successMetrics: 'Métricas de Sucesso',
    howWeKnow: 'Como saberemos que está funcionando?',
    expectedTimeframe: 'Prazo esperado para os resultados',
    ideal6Months: 'Cenário ideal em 6 meses',

    // Settings ICP
    icpTitle: 'Perfil de Cliente Ideal (ICP)',
    icpDesc: 'Defina seu cliente ideal para obter melhores outputs de IA, pontuação e segmentação.',
    targetIndustries: 'Indústrias-Alvo',
    addIndustry: 'Adicionar indústria...',
    companySizes: 'Tamanhos de Empresa',
    locations: 'Localizações',
    addLocation: 'Adicionar localização...',
    jobTitles: 'Cargos / Funções',
    addJobTitle: 'Adicionar cargo...',
    painPoints: 'Dores',
    addPainPoint: 'Adicionar dor...',
    budgetRange: 'Faixa de Orçamento',
    decisionCriteria: 'Critérios de Decisão',
    primaryAudience: 'Público Primário',
    secondaryAudience: 'Público Secundário',
    decisionMakerProfile: 'Perfil do Tomador de Decisão',
    mainDesires: 'Principais Desejos / Objetivos',
    commonObjections: 'Objeções Comuns',
    awarenessLevel: 'Nível de Consciência',
    saveICP: 'Salvar Config. ICP',
    notForLabel: 'Para quem NÃO é?',

    // Settings AI
    agentName: 'Nome do Agente',
    agentNameDesc: 'Personalize o nome do seu agente de IA exibido na barra lateral e no chat.',
    saveAgentName: 'Salvar Nome do Agente',
    aiConfiguration: 'Configuração de IA',
    aiConfigDesc: 'Configure a geração de imagens com IA e o nome do seu agente pessoal.',
    personalAgentName: 'Nome do Agente de IA Pessoal',
    personalAgentDesc: 'Este nome aparece na barra lateral e no chat de IA. Sua equipe verá este rótulo.',
    agentNameHint: 'Deixe em branco para usar o padrão "Bmapz AI".',
    imageProvider: 'Provedor de Geração de Imagens',
    imageProviderDesc: 'Escolha qual IA gera imagens na plataforma (criativos de anúncios, posts sociais, etc.)',
    dalleModel: 'Modelo DALL-E:',

    // Subscription
    subscriptionDesc: 'Gerencie sua assinatura, créditos e add-ons',
    seeInBilling: 'Ver no Billing',
    manageSubscription: 'Gerenciar Assinatura',
    viewPlans: 'Ver Planos',
    settingsSaved: 'Configurações salvas',

    // QuickStartGuide
    gotItSkip: 'Entendi, pular',
    gotIt: 'Entendi!',

    // Admin panel
    adminPanel: 'Painel Admin',
    adminDesc: 'Controle total da plataforma — usuários, empresas, assinaturas e cobrança',
    companies: 'Empresas',
    users: 'Usuários',
    activeSubs: 'Assinaturas Ativas',
    pending: 'Pendentes',
    pendingApproval: 'compra(s) aguardando aprovação manual',
    plan: 'Plano',
    status: 'Status',
    billingCycle: 'Ciclo de Cobrança',
    priceBRL: 'Preço (BRL/mês)',
    aiCreditsTotal: 'Total de Créditos IA',
    scanTokensLabel: 'Scan Tokens',
    actions: 'Ações',
    editSubscription: 'Editar Assinatura',
    grantCredits: 'Conceder Créditos',
    inviteUser: 'Convidar Usuário',
    createCompany: 'Criar Empresa',
    email: 'E-mail',
    role: 'Função',
    creditsToGrant: 'Créditos a Conceder',
    reason: 'Motivo',
    trialDays: 'Dias de Trial',

    // Social Media
    socialMediaTitle: 'Redes Sociais',
    socialMediaSubtitle: 'Planeje, crie e agende conteúdo + otimização de desempenho com IA',
    aiOptimize: 'Otimizar com IA',
    connectSocialAccounts: 'Conecte contas sociais em Configurações → Chaves de API para publicação automática',
    noPostsYet: 'Nenhum post ainda',
    noPostsScheduled: 'Nenhum post agendado ainda',
    platforms: 'Plataformas',
    addMedia: 'Adicionar Mídia',
    performance: 'Desempenho',
    sun: 'Dom', mon: 'Seg', tue: 'Ter', wed: 'Qua', thu: 'Qui', fri: 'Sex', sat: 'Sáb',
    smQs1: "Use o calendário para planejar e agendar posts. Clique em qualquer dia para criar um post nessa data.",
    smQs2: "Use o botão 'Gerar com IA' para criar conteúdo otimizado para Instagram, LinkedIn e mais.",
    smQs3: "Conecte suas contas sociais em Configurações → Chaves de API para ativar a publicação direta.",
    smQs4: "Use a aba Analytics para acompanhar o desempenho e o botão Otimizar com IA para sugestões de melhoria.",

    // Profile
    profileTitle: 'Perfil',
    myProfile: 'Meu Perfil',
    managePersonalInfo: 'Gerencie suas informações pessoais',
    fullName: 'Nome Completo',
    phoneNumber: 'Número de Telefone',
    timezone: 'Fuso Horário',
    emailCannotChange: 'O e-mail não pode ser alterado',
    accountInfo: 'Informações da Conta',
    memberSince: 'Membro desde',
    accountType: 'Tipo de Conta',
    profilePicture: 'Foto de Perfil',
    uploadPhoto: 'Enviar Foto',
    changePhoto: 'Trocar Foto',
    saving: 'Salvando...',
    profileSaved: 'Perfil salvo!',
    profileUpdated: 'Perfil atualizado com sucesso',
    failedToSave: 'Falha ao salvar perfil',
    failedToUpdate: 'Falha ao atualizar perfil',
    failedToUpload: 'Falha ao enviar imagem',
    selectImageFile: 'Por favor, selecione um arquivo de imagem',
    imageTooLarge: 'A imagem deve ter menos de 5MB',
    profilePictureUpdated: 'Foto de perfil atualizada',

    // Home QuickStart
    homeQs1: "Este painel mostra suas métricas principais, progressão do funil de vendas e atividade recente.",
    homeQs2: "Complete os passos 'Primeiros Passos' abaixo para desbloquear todo o potencial do BMAPZ.",
    homeQs3: "Use os botões de ação rápida acima para começar imediatamente.",
    homeQs4: "O Agente de IA na barra lateral pode ajudar a escrever mensagens, construir estratégias e analisar leads.",

    // Sales QuickStart
    salesQs1: "Adicione leads manualmente com o botão '+ Novo Lead', ou importe em massa pelo menu Vendas.",
    salesQs2: "Use a visão Kanban para arrastar leads entre etapas do funil, ou mude para a visão de Lista para uma visão estilo planilha.",
    salesQs3: "Clique em qualquer card de lead para abrir seu perfil completo — adicione notas, envie mensagens, execute análise de IA e inscreva em fluxos.",
    salesQs4: "Use o painel de Filtros para filtrar leads por pontuação ICP, valor, origem ou associação a listas.",

    // Sales additional
    leadUpdated: 'Lead atualizado',
    noActiveWorkflows: 'Nenhum fluxo ativo',
    noDraftWorkflows: 'Nenhum rascunho de fluxo',
    noInactiveWorkflows: 'Nenhum fluxo inativo',

    // Integrations
    stepByStep: 'Guia passo a passo',
    openPlatform: 'Abrir Plataforma →',
    awaitingSetup: 'Aguardando configuração da plataforma',
    connectionFailed: 'Conexão falhou',
    connected: 'Conectado',
    testingConnection: 'Testando conexão...',
    saveAndConnect: 'Salvar e Conectar',
    howToConnect: 'Como conectar',

    // Common extras
    searchPlaceholder: 'Buscar...',
    noResultsFound: 'Nenhum resultado encontrado',
    copyToClipboard: 'Copiar',
    copied: 'Copiado!',
    viewAll: 'Ver todos',
    seeAll: 'Ver tudo',
    required: 'Obrigatório',
    optional: 'opcional',
    na: 'N/D',
    yes: 'Sim',
    no: 'Não',
    on: 'Ligado',
    off: 'Desligado',
    active: 'Ativo',
    draft: 'Rascunho',
    inactive: 'Inativo',
    complete: 'Concluído',
    generating: 'Gerando...',
    noData: 'Nenhum dado disponível',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    // Saved preference first, then browser locale, then default to en
    const saved = localStorage.getItem('bmapz_language');
    if (saved === 'en' || saved === 'pt-BR') return saved;
    const browserLang = (typeof navigator !== 'undefined' && navigator.language) || 'en';
    return browserLang.toLowerCase().startsWith('pt') ? 'pt-BR' : 'en';
  });

  // Reflect language on <html lang="..."> for accessibility + SEO
  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language === 'pt-BR' ? 'pt-BR' : 'en';
    }
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const changeLanguage = (lang) => {
    if (lang !== 'en' && lang !== 'pt-BR') lang = 'en';
    setLanguage(lang);
    localStorage.setItem('bmapz_language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t, isPt: language === 'pt-BR' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;